[package]
name = "customized-integration-tests"
version = "0.0.0"
publish = false
edition = "2021"

[features]
default = ["hardware-dsa"]
hardware-dsa = ["dep:idxd-rust"]

[dependencies]
idxd-rust = { path = "../../../idxd-rust", optional = true }
prost = { path = "../prost/prost" }
tonic = { path = "../tonic" }

[build-dependencies]
prost-build = { path = "../prost/prost-build" }

[dev-dependencies]
criterion = { version = "0.8", default-features = false }

[[bench]]
name = "async_payload_encode"
harness = false
