[package]
name = "customized-integration-tests"
version = "0.0.0"
publish = false
edition = "2021"

[features]
default = ["hardware-dsa"]
hardware-dsa = ["dep:idxd-rust"]

[dependencies]
idxd-rust = { path = "../../../idxd-rust", optional = true }
prost = { path = "../prost/prost" }
tonic = { path = "../tonic" }
